<<<<<<< HEAD
# Generated by Django 5.1.4 on 2024-12-20 14:05

=======
# Generated by Django 5.1.4 on 2024-12-22 14:03

import django.db.models.deletion
>>>>>>> 0e4551c (feat: categories and subcategories relationship completed)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('categories', '0001_initial'),
>>>>>>> 0e4551c (feat: categories and subcategories relationship completed)
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=20, unique=True)),
=======
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
>>>>>>> 0e4551c (feat: categories and subcategories relationship completed)
            ],
        ),
    ]
