# Generated by Django 5.1.4 on 2025-01-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_options_order_quantity_order_reward_and_more'),
        ('rewards', '0003_rename_create_at_reward_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='rewards.reward'),
        ),
    ]
