# Generated by Django 5.1.4 on 2024-12-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="create_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="update_at",
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
