# Generated by Django 5.1.4 on 2025-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_create_at_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_userprofile', 'Can view user profile'), ('change_userprofile', 'Can change user profile'), ('delete_userprofile', 'Can delete user profile')]},
        ),
    ]
