# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_userprofile', 'Can view user profile'), ('can_change_userprofile', 'Can change user profile'), ('can_delete_userprofile', 'Can delete user profile')]},
        ),
    ]
