# Generated by Django 5.1.4 on 2024-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledges_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('pledges_date', models.DateTimeField()),
                ('payment_status', models.CharField(choices=[('PENDING', '待付款'), ('PAID', '已付款'), ('FAILED', '付款失敗'), ('REFUNDED', '已退款')], max_length=10)),
            ],
        ),
    ]
