# Generated by Django 5.1.4 on 2024-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100, null=True)),
                ('cover_image', models.FileField(null=True, upload_to='uploads/')),
                ('raised_amount', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('goal_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('start_at', models.DateTimeField(null=True)),
                ('end_at', models.DateTimeField()),
                ('story', models.TextField()),
                ('location', models.CharField(max_length=100, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
