# Generated by Django 5.1.4 on 2024-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_account'),
        ('subcategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subcategories',
            field=models.ManyToManyField(related_name='projects', to='subcategories.subcategory'),
        ),
    ]
