# Generated by Django 5.1.4 on 2024-12-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', '待上架'), ('live', '已上架'), ('ended', '已下架')], default='pending', max_length=10),
        ),
    ]
