# Generated by Django 5.1.4 on 2024-12-23 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_status'),
        ('rewards', '0002_reward_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.reward')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sponsor_account',
            field=models.ManyToManyField(related_name='sponsor_project', through='projects.Sponsor', to=settings.AUTH_USER_MODEL),
        ),
    ]
