# Generated by Django 5.1.4 on 2024-12-29 09:06

import autoslug.fields
import projects.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_rename_create_at_project_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=projects.models.generate_random_slug,
                editable=False,
                null=True,
                populate_from=projects.models.generate_random_slug,
                unique=True,
            ),
        ),
    ]
