# Generated by Django 5.1.4 on 2025-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_sponsor_project_sponsor_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectproject',
            options={'permissions': [('view_custom_collectproject', 'Can view custom collect project'), ('add_custom_collectproject', 'Can add custom collect project'), ('change_custom_collectproject', 'Can change custom collect project'), ('delete_custom_collectproject', 'Can delete custom collect project')]},
        ),
        migrations.AlterModelOptions(
            name='favoriteprject',
            options={'permissions': [('view_custom_favoriteproject', 'Can view custom favorite project'), ('add_custom_favoriteproject', 'Can add custom favorite project'), ('change_custom_favoriteproject', 'Can change custom favorite project'), ('delete_custom_favoriteproject', 'Can delete custom favorite project')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('view_custom_project', 'Can view custom project'), ('add_custom_project', 'Can add custom project'), ('change_custom_project', 'Can change custom project'), ('delete_custom_project', 'Can delete custom project')]},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'permissions': [('view_custom_sponsor', 'Can view custom sponsor'), ('add_custom_sponsor', 'Can add custom sponsor'), ('change_custom_sponsor', 'Can change custom sponsor'), ('delete_custom_sponsor', 'Can delete custom sponsor')]},
        ),
    ]
