# Generated by Django 5.1.4 on 2025-01-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_sponsor_project_sponsor_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.FileField(null=True, upload_to='cover_img/'),
        ),
    ]
