# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_collectproject_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectproject',
            options={'permissions': [('can_view_collectproject', 'Can view collect project'), ('can_add_collectproject', 'Can add collect project'), ('can_change_collectproject', 'Can change collect project'), ('can_delete_collectproject', 'Can delete collect project')]},
        ),
        migrations.AlterModelOptions(
            name='favoriteprject',
            options={'permissions': [('can_view_favoriteproject', 'Can view favorite project'), ('can_add_favoriteproject', 'Can add favorite project'), ('can_change_favoriteproject', 'Can change favorite project'), ('can_delete_favoriteproject', 'Can delete favorite project')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_view_project', 'Can view project'), ('can_add_project', 'Can add project'), ('can_change_project', 'Can change project'), ('can_delete_project', 'Can delete project')]},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'permissions': [('can_view_sponsor', 'Can view sponsor'), ('can_add_sponsor', 'Can add sponsor'), ('can_change_sponsor', 'Can change sponsor'), ('can_delete_sponsor', 'Can delete sponsor')]},
        ),
    ]
