# Generated by Django 5.1.4 on 2025-01-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_parent_alter_category_title'),
        ('projects', '0009_projectcategory_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_project_categories', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', through='projects.ProjectCategory', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_categories', to='categories.category'),
        ),
    ]
