# Generated by Django 5.1.4 on 2025-01-07 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_parent_alter_category_title'),
        ('projects', '0010_projectcategory_subcategory_alter_project_categories_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectcategory',
            unique_together={('project', 'category')},
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(through='projects.ProjectCategory', to='categories.category'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='subcategory',
        ),
    ]
