# Generated by Django 5.1.4 on 2025-01-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_cover_image'),
        ('projects', '0011_alter_projectcategory_unique_together_and_more'),
    ]

    operations = [
    ]
