# Generated by Django 5.1.4 on 2025-01-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_project_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectproject',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='favoriteprject',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
