# Generated by Django 5.1.4 on 2025-01-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_raised_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['-created_at']},
        ),
    ]
