# Generated by Django 5.1.4 on 2024-12-29 10:17

import autoslug.fields
import comments.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=comments.models.generate_random_slug, editable=False, null=True, populate_from=comments.models.generate_random_slug, unique=True),
        ),
    ]
