# Generated by Django 5.1.4 on 2025-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_rename_create_at_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('view_custom_comment', 'Can view custom comment'), ('add_custom_comment', 'Can add custom comment'), ('change_custom_comment', 'Can change custom comment'), ('delete_custom_comment', 'Can delete custom comment')]},
        ),
    ]
