# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_view_comment', 'Can view comment'), ('can_add_comment', 'Can add comment'), ('can_change_comment', 'Can change comment'), ('can_delete_comment', 'Can delete comment')]},
        ),
    ]
