# Generated by Django 5.1.4 on 2024-12-29 10:20

import autoslug.fields
import update_records.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_records', '0002_updaterecord_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterecord',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=update_records.models.generate_random_slug, editable=False, null=True, populate_from=update_records.models.generate_random_slug, unique=True),
        ),
    ]
