# Generated by Django 5.1.4 on 2025-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_records', '0003_updaterecord_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterecord',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
