# Generated by Django 5.1.4 on 2025-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_records', '0003_updaterecord_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updaterecord',
            options={'permissions': [('view_custom_updaterecord', 'Can view custom update record'), ('add_custom_updaterecord', 'Can add custom update record'), ('change_custom_updaterecord', 'Can change custom update record'), ('delete_custom_updaterecord', 'Can delete custom update record')]},
        ),
    ]
