# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_records', '0004_alter_updaterecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updaterecord',
            options={'permissions': [('can_view_updaterecord', 'Can view update record'), ('can_add_updaterecord', 'Can add update record'), ('can_change_updaterecord', 'Can change update record'), ('can_delete_updaterecord', 'Can delete update record')]},
        ),
    ]
