# Generated by Django 5.1.4 on 2025-01-13 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update_records', '0004_updaterecord_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='updaterecord',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='update_records', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
