# Generated by Django 5.1.4 on 2025-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_parent_alter_category_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('view_custom_category', 'Can view custom category'), ('add_custom_category', 'Can add custom category'), ('change_custom_category', 'Can change custom category'), ('delete_custom_category', 'Can delete custom category')]},
        ),
    ]
