# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': [('can_view_category', 'Can view category'), ('can_add_category', 'Can add category'), ('can_change_category', 'Can change category'), ('can_delete_category', 'Can delete category')]},
        ),
    ]
