# Generated by Django 5.1.4 on 2024-12-17 08:59

import rewards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('ship_to', models.TextField()),
                ('shipping_detail', models.TextField(blank=True)),
                ('estimated_delivery', models.DateField(default=rewards.models.default_delivery_date)),
                ('quantity', models.IntegerField(default=1)),
                ('optional_adds_on', models.TextField(blank=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
