# Generated by Django 5.1.4 on 2024-12-29 12:55

import autoslug.fields
import rewards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=rewards.models.generate_random_slug, editable=False, null=True, populate_from=rewards.models.generate_random_slug, unique=True),
        ),
    ]
