# Generated by Django 5.1.4 on 2024-12-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_reward_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reward',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='optional_adds_on',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='ship_to',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='shipping_detail',
        ),
        migrations.AlterField(
            model_name='reward',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OptionalAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('rewards', models.ManyToManyField(blank=True, to='rewards.reward')),
            ],
        ),
        migrations.CreateModel(
            name='RewardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('rewards', models.ManyToManyField(blank=True, to='rewards.reward')),
            ],
        ),
    ]
