# Generated by Django 5.1.4 on 2025-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rename_create_at_reward_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionaladd',
            options={'permissions': [('view_custom_optionaladd', 'Can view custom optional add'), ('add_custom_optionaladd', 'Can add custom optional add'), ('change_custom_optionaladd', 'Can change custom optional add'), ('delete_custom_optionaladd', 'Can delete custom optional add')]},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'permissions': [('view_custom_reward', 'Can view custom reward'), ('add_custom_reward', 'Can add custom reward'), ('change_custom_reward', 'Can change custom reward'), ('delete_custom_reward', 'Can delete custom reward')]},
        ),
        migrations.AlterModelOptions(
            name='rewardproduct',
            options={'permissions': [('view_custom_rewardproduct', 'Can view custom reward product'), ('add_custom_rewardproduct', 'Can add custom reward product'), ('change_custom_rewardproduct', 'Can change custom reward product'), ('delete_custom_rewardproduct', 'Can delete custom reward product')]},
        ),
    ]
