# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_optionaladd_options_alter_reward_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionaladd',
            options={'permissions': [('can_view_optionaladd', 'Can view optional add'), ('can_add_optionaladd', 'Can add optional add'), ('can_change_optionaladd', 'Can change optional add'), ('can_delete_optionaladd', 'Can delete optional add')]},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'permissions': [('can_view_reward', 'Can view reward'), ('can_add_reward', 'Can add reward'), ('can_change_reward', 'Can change reward'), ('can_delete_reward', 'Can delete reward')]},
        ),
        migrations.AlterModelOptions(
            name='rewardproduct',
            options={'permissions': [('can_view_rewardproduct', 'Can view reward product'), ('can_add_rewardproduct', 'Can add reward product'), ('can_change_rewardproduct', 'Can change reward product'), ('can_delete_rewardproduct', 'Can delete reward product')]},
        ),
    ]
