# Generated by Django 5.1.4 on 2025-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_reward_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionaladd',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardproduct',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
