# Generated by Django 5.1.4 on 2024-12-21 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_project'),
        ('comments_replies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsreplies',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comments.comment'),
            preserve_default=False,
        ),
    ]
