# Generated by Django 5.1.4 on 2025-01-05 13:18

import autoslug.fields
import chats.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from=chats.models.generate_random_slug, unique=True),
        ),
    ]
