# Generated by Django 5.1.4 on 2024-12-29 10:17

import autoslug.fields
import faqs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_faq_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=faqs.models.generate_random_slug, editable=False, null=True, populate_from=faqs.models.generate_random_slug, unique=True),
        ),
    ]
