# Generated by Django 5.1.4 on 2025-01-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_faq_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'permissions': [('view_custom_faq', 'Can view custom FAQ'), ('add_custom_faq', 'Can add custom FAQ'), ('change_custom_faq', 'Can change custom FAQ'), ('delete_custom_faq', 'Can delete custom FAQ')]},
        ),
    ]
