# Generated by Django 5.1.4 on 2025-01-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'permissions': [('can_view_faq', 'Can view FAQ'), ('can_add_faq', 'Can add FAQ'), ('can_change_faq', 'Can change FAQ'), ('can_delete_faq', 'Can delete FAQ')]},
        ),
    ]
