# Generated by Django 5.1.4 on 2025-01-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0004_alter_faq_options_rename_create_at_faq_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='deleted_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
